<?php

namespace Camoo\Config\Test\Parser;

use Camoo\Config\Enum\Parser;
use Camoo\Config\Parser\Json;
use PHPUnit\Framework\TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-04-21 at 22:37:22.
 */
class JsonTest extends TestCase
{
    /** @var Json */
    protected $json;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->json = new Json();
    }

    /** @covers \Camoo\Config\Parser\Json::getSupportedExtensions() */
    public function testGetSupportedExtensions()
    {
        $expected = [Parser::JSON];
        $actual = $this->json->getSupportedExtensions();
        $this->assertSame($expected, $actual);
    }

    /**
     * @covers \Camoo\Config\Parser\Json::parseFile()
     * @covers \Camoo\Config\Parser\Json::parse()
     */
    public function testLoadInvalidJson()
    {
        $this->expectException(\Camoo\Config\Exception\ParseException::class);
        $this->expectExceptionMessage('Syntax error');
        $this->json->parseFile(__DIR__ . '/../mocks/fail/error.json');
    }

    /**
     * @covers \Camoo\Config\Parser\Json::parseFile()
     * @covers \Camoo\Config\Parser\Json::parseString()
     * @covers \Camoo\Config\Parser\Json::parse()
     */
    public function testLoadJson()
    {
        $file = $this->json->parseFile(__DIR__ . '/../mocks/pass/config.json');
        $string = $this->json->parseString(file_get_contents(__DIR__ . '/../mocks/pass/config.json'));

        $this->assertSame('localhost', $file['host']);
        $this->assertSame(80, $file['port']);

        $this->assertSame('localhost', $string['host']);
        $this->assertSame(80, $string['port']);
    }
}
